name: OWASP ZAP API Scan

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      api1:
        description: 'API Endpoint 1'
        required: true
      api2:
        description: 'API Endpoint 2'
        required: true
      api3:
        description: 'API Endpoint 3'
        required: true
      api4:
        description: 'API Endpoint 4'
        required: true
      api5:
        description: 'API Endpoint 5'
        required: true

jobs:
  zap_scan:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        api: 
          - ${{ github.event.inputs.api1 }}
          - ${{ github.event.inputs.api2 }}
          - ${{ github.event.inputs.api3 }}
          - ${{ github.event.inputs.api4 }}
          - ${{ github.event.inputs.api5 }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: tantrummaster
        password: dckr_pat_RDR6QwvY94nJ-J2SKyjiPTKnpoU

    - name: Pull OWASP ZAP Docker image
      run: |
        docker pull zaproxy/zap-stable

    - name: Sanitize API URL for file paths
      id: sanitize
      run: |
        SAFE_API=$(echo "${{ matrix.api }}" | sed 's/[\/:]/_/g')
        echo "SAFE_API=${SAFE_API}" >> $GITHUB_ENV

    - name: Run ZAP Full Scan on ${{ matrix.api }}
      run: |
        mkdir -p ${{ github.workspace }}/report-${{ env.SAFE_API }}
        chmod 777 ${{ github.workspace }}/report-${{ env.SAFE_API }}
        docker run -v ${{ github.workspace }}/report-${{ env.SAFE_API }}:/zap/wrk:rw -t ghcr.io/zaproxy/zaproxy:stable zap-full-scan.py -t ${{ matrix.api }} -r /zap/wrk/testreport-${{ env.SAFE_API }}.html || true
        echo "Checking if report exists..."
        ls -l ${{ github.workspace }}/report-${{ env.SAFE_API }}
        
    - name: Upload ZAP Report for ${{ matrix.api }}
      uses: actions/upload-artifact@v3
      with:
        name: ZAP Report ${{ matrix.api }}
        path: ${{ github.workspace }}/report-${{ env.SAFE_API }}/testreport-${{ env.SAFE_API }}.html
