name: Trigger Scan

on:
  workflow_dispatch:
    inputs:
      openapi_file:
        description: 'Path to the OpenAPI.yaml file to scan'
        required: true

permissions:
  issues: write  # Grant permission to create and manage issues

jobs:
  update-and-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      - name: Start the server
        run: npm start &
        
      - name: Wait for the server to start
        run: sleep 20  # Adjust this as needed to ensure the server is up

      - name: ZAP API Scan
        uses: zaproxy/action-api-scan@v0.7.0
        with:
          target: "${{ github.event.inputs.openapi_file }}"
          rules: "rules.json"  # Specify path to your ZAP rules file if needed
          context: "context.json"  # Specify path to your ZAP context file if needed

      - name: Upload ZAP Scan Results
        uses: actions/upload-artifact@v4
        with:
          name: zap-scan-results
          path: zap_scan_results.xml
