name: Trigger Scan

on:
  workflow_dispatch:
    inputs:
      repo_url:
        description: 'Repository URL to update in config.json'
        required: true

permissions:
  issues: write  # Grants permission to create and manage issues

jobs:
  update-and-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Update config.json with the new URL
        run: |
          # Define the path to config.json
          CONFIG_FILE="config.json"

          # Update the repoPath in config.json using jq
          jq --arg url "${{ github.event.inputs.repo_url }}" '.repoPath = $url' "$CONFIG_FILE" > tmp.$$.json && mv tmp.$$.json "$CONFIG_FILE"

          echo "Updated repoPath in config.json to ${{ github.event.inputs.repo_url }}"

      - name: Run JavaScript project
        run: |
          npm install
          npm run start

      - name: Upload OpenAPI Specification (converted from Postman Collection)
        uses: actions/upload-artifact@v4
        with:
          name: openapi-spec
          path: openapi_spec.json  # Make sure this file exists

      - name: Download OpenAPI Spec
        run: |
          # Download the OpenAPI spec to the ZAP working directory
          cp openapi_spec.json /home/runner/work/ApiScanner/ApiScanner/openapi_spec.json

      - name: ZAP API Scan with OpenAPI Spec
        uses: zaproxy/action-api-scan@v0.7.0
        with:
          target: "file:/zap/wrk/openapi_spec.json"
          format: "openapi"
          cmd_options: "-J report_json.json -w report_md.md -r report_html.html"

      - name: Upload ZAP Scan Results
        uses: actions/upload-artifact@v4
        with:
          name: zap-report
          path: report_html.html
