name: Trigger Scan

on:
  workflow_dispatch:
    inputs:
      repo_url:
        description: 'Repository URL to update in config.json'
        required: true

permissions:
  issues: write  # Add this line to grant permission to create and manage issues

jobs:
  update-and-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Update config.json with the new URL
        run: |
          # Define the path to config.json
          CONFIG_FILE="config.json"

          # Update the repoPath in config.json using jq
          jq --arg url "${{ github.event.inputs.repo_url }}" '.repoPath = $url' "$CONFIG_FILE" > tmp.$$.json && mv tmp.$$.json "$CONFIG_FILE"

          echo "Updated repoPath in config.json to ${{ github.event.inputs.repo_url }}"

      - name: Run JavaScript project
        run: |
          npm install
          npm run start

      - name: Upload Postman Collection
        uses: actions/upload-artifact@v4
        with:
          name: postman-collection
          path: postman_collection.json

      - name: ZAP API Scan
        uses: zaproxy/action-api-scan@v0.7.0
        with:
          target: OpenAPI.yml
          rules: "rules.json"  # Specify path to your ZAP rules file if needed
          context: "context.json"  # Specify path to your ZAP context file if needed

      - name: Upload ZAP Scan Results
        uses: actions/upload-artifact@v4
        with:
          name: zap-scan-results
          path: zap_scan_results.xml
