RedWater
_redwater
Huh ? Hi There!

A wild 
Navneethan
 appeared.
 — 13/10/2022 15:54
nik1947
 joined the party.
 — 13/10/2022 16:25
DraegonWraith — 13/10/2022 16:27
DraegonWraith — 13/10/2022 16:28
nik1947 — 13/10/2022 16:30
👍
Everyone welcome 
Explishit
!
 — 14/10/2022 18:46
Navneethan — 16/10/2022 16:12
fifa 14 khel raha hai viplav ?
Explishit — 16/10/2022 16:13
raha tha
Navneethan — 16/10/2022 16:13
@Explishit
accha
@DraegonWraith
DraegonWraith — 18/10/2022 15:08
@nik1947
aa na
jaldi
DraegonWraith — 18/10/2022 15:21
667429
236510
Navneethan — 18/10/2022 16:18
Chalo bye boys ab kaal hi khelunga
nik1947 — 19/10/2022 15:18
aajao
siddhant
viplav
navneethan
@DraegonWraith
@Explishit
@Navneethan
DraegonWraith — 19/10/2022 15:56
607080
nik1947 — 20/10/2022 16:52
@pseudo_force @DraegonWraith
Yay you made it, 
Harbinger
!
 — 27/06/2023 15:45
RedWater
 is here.
 — 28/06/2023 23:47
DraegonWraith — 14/08/2024 21:55
https://www.npmjs.com/package/nodejs-api-discovery?activeTab=readme
npm
nodejs-api-discovery
Nodejs API discovery CLI and postman collection generator. Latest version: 1.2.1, last published: 19 days ago. Start using nodejs-api-discovery in your project by running `npm i nodejs-api-discovery`. There are no other projects in the npm registry using nodejs-api-discovery.
Image
DraegonWraith — 15/08/2024 22:16
https://learnandshare.live/blogs/blog-details/8/apis-scan-through-zap
Vikash - Learn and Share Live
A place where all the learnings are captured to help all the needy who wants to get their problem resolved.
https://www.zaproxy.org/docs/docker/api-scan/
ZAP – ZAP - API Scan
The world’s most widely used web app scanner. Free and open source. ZAP is a community project actively maintained by a dedicated international team, and a GitHub Top 1000 project.
Asmodeus — Yesterday at 22:22
Image
DraegonWraith — Yesterday at 22:29
Run p2o ./postman_collection.json -f ./openapi.yaml -o ./options.json
/home/runner/work/_temp/17949c6d-e1ae-45f6-9dd6-3af23d112fa2.sh: line 1: p2o: command not found
Error: Process completed with exit code 127.
Asmodeus — Yesterday at 22:31
name: Install dependencies
    run: |
      pip install p2o
DraegonWraith — Yesterday at 22:35
un pip install p2o

Defaulting to user installation because normal site-packages is not writeable
ERROR: Could not find a version that satisfies the requirement p2o (from versions: none)
ERROR: No matching distribution found for p2o
Asmodeus — Yesterday at 22:36
https://gist.github.com/0xdevalias/5fecf0db3bd9cc7465e42616061e1ab0
Gist
Exploring tools that allow converting a JSON response automagically...
Exploring tools that allow converting a JSON response automagically into an OpenAPI / Swagger spec. - converting-json-to-openapi-swagger-spec.md
Exploring tools that allow converting a JSON response automagically...
DraegonWraith — Yesterday at 22:56
```
name: Trigger Scan

on:
  workflow_dispatch:
    inputs:
Expand
message.txt
3 KB
```
name: Trigger Scan

on:
  workflow_dispatch:
    inputs:
Expand
message.txt
3 KB
DraegonWraith — Yesterday at 23:06
https://github.com/Siddhant02082002/piyush-check
GitHub
GitHub - Siddhant02082002/piyush-check
Contribute to Siddhant02082002/piyush-check development by creating an account on GitHub.
GitHub - Siddhant02082002/piyush-check
https://github.com/Siddhant02082002/piyush-check/actions/runs/10423945207/workflow
GitHub
Update main.yml · Siddhant02082002/piyush-check@8c4f558
Contribute to Siddhant02082002/piyush-check development by creating an account on GitHub.
Update main.yml · Siddhant02082002/piyush-check@8c4f558
DraegonWraith — Yesterday at 23:23
```
{
  "info": {
    "name": "admin",
    "description": "Collection generated programmatically from Node.js server",
    "schema": "https://schema.getpostman.com/json/collection/v2.1.0/collection.json"
Expand
message.txt
3 KB
DraegonWraith — Today at 01:12
async function runTool(writeCollection = false) {
  try {
    console.log("Hello")
    const endpoints = await discoverEndpoints(config);
    console.log(endpoints);
    await generatePostmanCollection(
      endpoints,
      config.baseUrl,
      config.postmanKey,
      config.workspaceId,
      config.collectionName,
      writeCollection
    );
    console.log("Postman collection generated successfully!");
  } catch (error) {
    console.error("Error generating Postman collection:", error.message);
  }
}
#!/usr/bin/env node

import fs from "fs";
import { program } from "commander";
import { discoverEndpoints, generatePostmanCollection } from "./lib/index.mjs";

// Load configuration based on provided config file
program
  .option("-c, --config <configPath>", "Specify config file path")
  .parse(process.argv);

// Extract configPath from command-line arguments or fallback to default
const configPath = program.config || "./config.json";

// Read and parse the configuration file
let config;
try {
  config = JSON.parse(fs.readFileSync(configPath, "utf8"));
} catch (err) {
  console.error("Error reading or parsing configuration file:", err);
  process.exit(1);
}

// Function to run API discovery and collection generation
async function runTool(writeCollection = false) {
  try {
    console.log("Hello")
    const endpoints = await discoverEndpoints(config);
    console.log(endpoints);
    await generatePostmanCollection(
      endpoints,
      config.baseUrl,
      config.postmanKey,
      config.workspaceId,
      config.collectionName,
      writeCollection
    );
    console.log("Postman collection generated successfully!");
  } catch (error) {
    console.error("Error generating Postman collection:", error.message);
  }
}

// Run the tool based on command-line arguments
runTool(true); // Always write collection in CLI mode
Asmodeus — Today at 01:21
#!/usr/bin/env node

import fs from "fs";
import { program } from "commander";
import { discoverEndpoints, generatePostmanCollection } from "./lib/index.mjs";
import chokidar from "chokidar";  // Import chokidar for file watching
Expand
message.txt
3 KB
DraegonWraith — Today at 02:11
10578 [ZAP-Import-OpenAPI-1] WARN  org.zaproxy.zap.extension.openapi.ExtensionOpenApi - Failed to access URL: http://localhost:3000/refresh-tokens : org.apache.hc.client5.http.HttpHostConnectException : Connect to http://localhost:3000/ [localhost/127.0.0.1, localhost/0:0:0:0:0:0:0:1] failed: Connection refused (Connection refused)
name: Trigger Scan

on:
  workflow_dispatch:
    inputs:
      repo_url:
Expand
message.txt
3 KB
DraegonWraith — Today at 14:15
ERROR [Errno 13] Permission denied: '/zap/wrk/zap_report.html'
2024-08-17 08:42:00,962 I/O error: [Errno 13] Permission denied: '/zap/wrk/zap_report.html'
Traceback (most recent call last):
  File "/zap/zap-api-scan.py", line 597, in main
    write_report(os.path.join(base_dir, report_html), zap.core.htmlreport())
  File "/zap/zap_common.py", line 569, in write_report
    with open(file_path, mode='wb') as f:
PermissionError: [Errno 13] Permission denied: '/zap/wrk/zap_report.html'
Found Java version 11.0.24
Available memory: 15981 MB
DraegonWraith — Today at 15:22
https://dev.to/kabartolo/how-to-document-an-express-api-with-swagger-ui-and-jsdoc-50do
DEV Community
How to Document an Express API with Swagger UI and JSDoc
JSDoc is a popular tool for generating documentation from comments in the source code of your app. Th...
How to Document an Express API with Swagger UI and JSDoc
Asmodeus — Today at 19:20
Attachment file type: archive
dashboard-app.zip
182.68 KB
DraegonWraith — Today at 22:57
openapi: 3.0.0
info:
  title: Your API Documentation
  version: 1.0.0
  description: API documentation
servers:
Expand
OpenAPI.yml
18 KB
name: Trigger Scan

on:
  workflow_dispatch:
    inputs:
      repo_url:
Expand
message.txt
3 KB
﻿
name: Trigger Scan

on:
  workflow_dispatch:
    inputs:
      repo_url:
        description: 'Repository URL to update in config.json'
        required: true

jobs:
  update-and-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Update config.json with the new URL
        run: |
          CONFIG_FILE="config.json"
          jq --arg url "${{ github.event.inputs.repo_url }}" '.repoPath = $url' "$CONFIG_FILE" > tmp.$$.json && mv tmp.$$.json "$CONFIG_FILE"
          echo "Updated repoPath in config.json to ${{ github.event.inputs.repo_url }}"

      - name: Run JavaScript project
        run: |
          npm install
          npm run start

      - name: Upload Postman Collection
        uses: actions/upload-artifact@v2
        with:
          name: postman-collection
          path: postman_collection.json
          
      - name: Download Postman Collection Artifact
        uses: actions/download-artifact@v2
        with:
            name: postman-collection
            path: ./

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: tantrummaster
          password: dckr_pat_RDR6QwvY94nJ-J2SKyjiPTKnpoU

      - name: Pull the latest ZAP Docker image
        run: docker pull zaproxy/zap-stable

      - name: Check if Postman Collection file exists
        run: ls -l postman_collection.json

      - name: Convert Postman to OpenAPI
        run: |
          npm install postman-to-openapi
      # - name: p2o
      #   run: |
      #     pip install p2o
          
        # npx postman-to-openapi postman_collection.json openapi.yaml
      - name: conversion
        run: |
          node p2o ./postman_collection.json -f ./openapi.yaml -o ./options.json

          
      - name: Upload OpenAPI file
        uses: actions/upload-artifact@v2
        with:
          name: openapi-file
          path: openapi.yaml

      - name: Run ZAP API Scan
        run: |
          docker run -t -v ${{ github.workspace }}:/zap/wrk zaproxy/zap-stable zap-api-scan.py \
            -t /zap/wrk/openapi.yaml \
            -f openapi \
            -r zap_report.html
#/zap/wrk/
      - name: Upload ZAP Report
        uses: actions/upload-artifact@v2
        with:
          name: zap-report
          path: zap_report.html
