name: OWASP ZAP API Scan

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      api1:
        description: 'https://github.com/Siddhant02082002/backend-testing2.0'
        required: true
      api2:
        description: 'https://github.com/Siddhant02082002/backend-testing2.0'
        required: true
      api3:
        description: 'https://github.com/Siddhant02082002/backend-testing2.0'
        required: true
      api4:
        description: 'https://github.com/Siddhant02082002/backend-testing2.0'
        required: true
      api5:
        description: 'https://github.com/Siddhant02082002/backend-testing2.0'
        required: true

jobs:
  zap_scan:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        api: 
          - ${{ github.event.inputs.api1 }}
          - ${{ github.event.inputs.api2 }}
          - ${{ github.event.inputs.api3 }}
          - ${{ github.event.inputs.api4 }}
          - ${{ github.event.inputs.api5 }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: tantrummaster
        password: dckr_pat_RDR6QwvY94nJ-J2SKyjiPTKnpoU

    - name: Pull OWASP ZAP Docker image
      run: |
        docker pull zaproxy/zap-stable
        
    - name: Run ZAP Full Scan on ${{ matrix.api }}
      run: |
        mkdir -p ${{ github.workspace }}/report-${{ matrix.api }}
        chmod 777 ${{ github.workspace }}/report-${{ matrix.api }}
        docker run -v ${{ github.workspace }}/report-${{ matrix.api }}:/zap/wrk:rw -t ghcr.io/zaproxy/zaproxy:stable zap-full-scan.py -t ${{ matrix.api }} -r /zap/wrk/testreport-${{ matrix.api }}.html || true
        echo "Checking if report exists..."
        ls -l ${{ github.workspace }}/report-${{ matrix.api }}
        
    - name: Upload ZAP Report for ${{ matrix.api }}
      uses: actions/upload-artifact@v3
      with:
        name: ZAP Report ${{ matrix.api }}
        path: ${{ github.workspace }}/report-${{ matrix.api }}/testreport-${{ matrix.api }}.html
