const axios = require('axios');

const token = 'YOUR_PERSONAL_ACCESS_TOKEN'; // Replace with your GitHub token
const owner = 'YOUR_GITHUB_USERNAME_OR_ORG';
const repo = 'YOUR_REPOSITORY_NAME';
const workflowId = 'YOUR_WORKFLOW_FILE_NAME.yml'; // or use the workflow ID
const ref = 'main'; // Branch name or Git reference

const triggerWorkflow = async () => {
  try {
    const response = await axios.post(
      `https://api.github.com/repos/${owner}/${repo}/actions/workflows/${workflowId}/dispatches`,
      {
        ref: ref
      },
      {
        headers: {
          'Authorization': `token ${token}`,
          'Accept': 'application/vnd.github.v3+json'
        }
      }
    );

    console.log('Workflow triggered:', response.data);
  } catch (error) {
    console.error('Error triggering workflow:', error.response ? error.response.data : error.message);
  }
};

triggerWorkflow();
