name: OWASP ZAP API Scan

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  zap_scan:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: tantrummaster
        password: dckr_pat_RDR6QwvY94nJ-J2SKyjiPTKnpoU

    - name: Pull OWASP ZAP Docker image
      run: |
        docker pull zaproxy/zap-stable
    - name: Run OWASP ZAP API Scan
      run: |
        docker run -v ${{ github.workspace }}:/zap/wrk zaproxy/zap-stable zap-api-scan.py -t "https://dummy-backend-check.onrender.com/api/users" -f openapi -r zap_report.html
        docker cp $(docker ps -q -l):/zap/zap_report.html ./zap_report.html
    - name: Upload ZAP Report
      uses: actions/upload-artifact@v3
      with:
        name: ZAP Report
        path: ./zap_report.html
