name: OWASP ZAP API Scan

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  zap_scan:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: tantrummaster
        password: dckr_pat_RDR6QwvY94nJ-J2SKyjiPTKnpoU

    - name: Pull OWASP ZAP Docker image
      run: |
        docker pull zaproxy/zap-stable
    - name: Run ZAP Full Scan
      run: |
        mkdir -p ${{ github.workspace }}/report
        chmod 777 ${{ github.workspace }}/report
        docker run -v ${{ github.workspace }}/report:/zap/wrk:rw -t ghcr.io/zaproxy/zaproxy:stable zap-full-scan.py -t https://dummy-backend-check.onrender.com/api/users -r /zap/wrk/testreport.html
        
    - name: Upload ZAP Report
      uses: actions/upload-artifact@v3
      with:
        name: ZAP Report
        path: ${{ github.workspace }}/report/testreport.html
