name: Trigger Postman Collection and ZAP Scan

on:
  workflow_dispatch:
    inputs:
      repo_url:
        description: 'Repository URL to update in config.json'
        required: true

jobs:
  update-and-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Update config.json with the new URL
        run: |
          CONFIG_FILE="config.json"
          jq --arg url "${{ github.event.inputs.repo_url }}" '.repoPath = $url' "$CONFIG_FILE" > tmp.$$.json && mv tmp.$$.json "$CONFIG_FILE"
          echo "Updated repoPath in config.json to ${{ github.event.inputs.repo_url }}"

      - name: Run JavaScript project
        run: |
          npm install
          npm run start

      - name: Run Postman Collection with Newman
        run: |
          npm install -g newman
          newman run postman_collection.json --global-var "baseUrl=http://localhost:3000" --reporters cli

      - name: Run ZAP Active Scan
        run: |
          # Assuming ZAP is running on localhost:8080
          zap-cli start --start-options '-config api.disablekey=true'
          zap-cli open-url http://localhost:3000
          zap-cli spider http://localhost:3000
          zap-cli active-scan http://localhost:3000
          zap-cli report -o zap-report.html -f html
          zap-cli stop

      - name: Upload ZAP Scan Report
        uses: actions/upload-artifact@v4
        with:
          name: zap-report
          path: zap-report.html
