name: Trigger Scan

on:
  workflow_dispatch:
    inputs:
      repo_url:
        description: 'Repository URL to update in config.json'
        required: true

jobs:
  update-and-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Update config.json with the new URL
        run: |
          # Define the path to config.json
          CONFIG_FILE="config.json"

          # Update the repoPath in config.json using jq
          jq --arg url "${{ github.event.inputs.repo_url }}" '.repoPath = $url' "$CONFIG_FILE" > tmp.$$.json && mv tmp.$$.json "$CONFIG_FILE"

          echo "Updated repoPath in config.json to ${{ github.event.inputs.repo_url }}"

      - name: Run JavaScript project
        run: |
          npm install
          npm run start

      - name: Upload Postman Collection
        uses: actions/upload-artifact@v2
        with:
          name: postman-collection
          path: postman_collection.json

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: tantrummaster
          password: dckr_pat_RDR6QwvY94nJ-J2SKyjiPTKnpoU

      - name: Pull the latest ZAP Docker image
        run: |
          docker pull zaproxy/zap-stable

      - name: Run ZAP API Scan
        run: |
          # Run ZAP API scan against the Postman collection
          docker run -t zaproxy/zap-stable zap-api-scan.py -t \
            -t /zap/wrk/postman_collection.json \
            -f openapi \
            -r zap_report.html

      - name: Upload ZAP Report
        uses: actions/upload-artifact@v2
        with:
          name: zap-report
          path: zap_report.html
