name: OWASP ZAP API Scan

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      api1:
        description: 'API Endpoint 1'
        required: true
      api2:
        description: 'API Endpoint 2'
        required: true
      api3:
        description: 'API Endpoint 3'
        required: true
      api4:
        description: 'API Endpoint 4'
        required: true
      api5:
        description: 'API Endpoint 5'
        required: true

jobs:
  zap_scan:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: tantrummaster
        password: dckr_pat_RDR6QwvY94nJ-J2SKyjiPTKnpoU

    - name: Pull OWASP ZAP Docker image
      run: |
        docker pull zaproxy/zap2docker-stable

    - name: Run ZAP Full Scans
      run: |
        for api in "${{ github.event.inputs.api1 }}" "${{ github.event.inputs.api2 }}" "${{ github.event.inputs.api3 }}" "${{ github.event.inputs.api4 }}" "${{ github.event.inputs.api5 }}"; do
          SAFE_API=$(echo "$api" | sed 's/[\/:]/_/g')
          mkdir -p ${{ github.workspace }}/report-${SAFE_API}
          chmod 777 ${{ github.workspace }}/report-${SAFE_API}
          docker run -v ${{ github.workspace }}/report-${SAFE_API}:/zap/wrk:rw -t zaproxy/zap2docker-stable zap-full-scan.py -t $api -r /zap/wrk/testreport-${SAFE_API}.html -daemon -m 10 || true
          echo "Checking if report exists for $api..."
          ls -l ${{ github.workspace }}/report-${SAFE_API}
        done

    - name: Upload ZAP Reports
      uses: actions/upload-artifact@v3
      with:
        name: ZAP Reports
        path: ${{ github.workspace }}/report-*/testreport-*.html
