name: Trigger Scan

on:
  workflow_dispatch:
    inputs:
      repo_url:
        description: 'Repository URL to update in config.json'
        required: true

jobs:
  update-and-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Update config.json with the new URL
        run: |
          CONFIG_FILE="config.json"
          jq --arg url "${{ github.event.inputs.repo_url }}" '.repoPath = $url' "$CONFIG_FILE" > tmp.$$.json && mv tmp.$$.json "$CONFIG_FILE"
          echo "Updated repoPath in config.json to ${{ github.event.inputs.repo_url }}"

      - name: Run JavaScript project
        run: |
          npm install
          npm run start

      - name: Upload Postman Collection
        uses: actions/upload-artifact@v4
        with:
          name: postman-collection
          path: postman_collection.json

      - name: Run OWASP ZAP Scan
        uses: zaproxy/action-full-scan@v0.8.0
        with:
          target: 'http://localhost:3000'
          cmd_options: '-configfile /home/runner/work/owasp.conf -J /home/runner/work/report_json.json -w /home/runner/work/report_md.md -r /home/runner/work/report_html.html'

      - name: List Working Directory
        run: ls -R /home/runner/work/

      - name: Print ZAP Logs
        run: ls -R /home/runner/work/ || echo "No logs found in /home/runner/work/"

      - name: Upload ZAP Scan Report
        uses: actions/upload-artifact@v4
        with:
          name: zap-report
          path: /home/runner/work/report_html.html
